# Generated by Django 2.2.7 on 2020-02-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Time_slots'),
        ),
    ]
