# Generated by Django 2.2.7 on 2020-02-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200218_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_slots',
            name='date',
        ),
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Time_slots'),
        ),
    ]
