# Generated by Django 2.2.7 on 2020-02-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200218_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_slots',
            name='room_id',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Time_slots'),
        ),
    ]
