# Generated by Django 2.2.7 on 2020-03-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200224_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Time_slots'),
        ),
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Time_slots')),
            ],
        ),
    ]
